set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports D_Q_Asy]
set_property IOSTANDARD LVCMOS33 [get_ports D_Q_Syn]
set_property IOSTANDARD LVCMOS33 [get_ports JK_Q_Asy]
set_property IOSTANDARD LVCMOS33 [get_ports JK_Q_Syn]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports SR_Q_Asy]
set_property IOSTANDARD LVCMOS33 [get_ports SR_Q_Syn]
set_property IOSTANDARD LVCMOS33 [get_ports T]
set_property IOSTANDARD LVCMOS33 [get_ports T_Q_Asy]
set_property IOSTANDARD LVCMOS33 [get_ports T_Q_Syn]
set_property IOSTANDARD LVCMOS33 [get_ports {JK[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {JK[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SR[0]}]
set_property PACKAGE_PIN U18 [get_ports CLK]
set_property PACKAGE_PIN M19 [get_ports D]
set_property PACKAGE_PIN Y11 [get_ports D_Q_Asy]
set_property PACKAGE_PIN Y12 [get_ports D_Q_Syn]
set_property PACKAGE_PIN W18 [get_ports RESET]
set_property PACKAGE_PIN M20 [get_ports T]
set_property PACKAGE_PIN W11 [get_ports T_Q_Asy]
set_property PACKAGE_PIN V11 [get_ports T_Q_Syn]
set_property PACKAGE_PIN W16 [get_ports {SR[0]}]
set_property PACKAGE_PIN V16 [get_ports {SR[1]}]
set_property PACKAGE_PIN U17 [get_ports SR_Q_Syn]
set_property PACKAGE_PIN R16 [get_ports SR_Q_Asy]
set_property PACKAGE_PIN V12 [get_ports {JK[1]}]
set_property PACKAGE_PIN W13 [get_ports {JK[0]}]
set_property PACKAGE_PIN U15 [get_ports JK_Q_Asy]
set_property PACKAGE_PIN T15 [get_ports JK_Q_Syn]
# PYNQ-Z2 보드의 125MHz 클럭 설정 (주기: 8.0ns)
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} [get_ports CLK]

# CLK 포트를 FPGA의 H16번 핀에 연결
set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports CLK]
